#language: java
#jdk:
#  - openjdk11
#
#branches:
#  only:
#    - master
#    - develop
#
## Travis CI 서버의 Cache 활성화
#cache:
#  directories:
#    - '$HOME/.m2/repository'
#    - '$HOME/.gradle'
#
## clean 후 Build (Build시 자동으로 test 수행)
#script: "./gradlew clean build"
#
#after_success:
#  - ./gradlew jacocoTestReport coveralls

language: java
jdk:
  - openjdk11
branches:
  only:
    - master
    - develop
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
